apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bvmi7s9v1-go
  janus-idp.io/tekton: bvmi7s9v1-go
  backstage.io/kubernetes-id: bvmi7s9v1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bvmi7s9v1-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
