apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bvmi7s9v1-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:e2bd9d7450a20d831ef1751f0748f779cc71f060@sha256:34a3c5f5de66b37724353479c258e95dd129be2ef0e58bfe3d13399dedc62d0c
          name: container-image
